//! Basic emit and label helpers.

use tc24r_codegen_state::CodegenState;

/// Append one line of assembly to the output buffer.
pub fn emit(state: &mut CodegenState, line: &str) {
    state.out.push_str(line);
    state.out.push('\n');
}

/// Allocate a fresh unique label and return it.
pub fn new_label(state: &mut CodegenState) -> String {
    let label = format!("L{}", state.label_counter);
    state.label_counter += 1;
    label
}

/// Emit an unconditional branch to target.
///
/// Uses short `bra` for local labels (Lnn) which are typically nearby.
/// Uses long form (la r2 + jmp) for global/function labels which may be far.
pub fn emit_bra(state: &mut CodegenState, target: &str) {
    if is_local_label(target) {
        emit(state, &format!("        bra     {target}"));
    } else {
        emit(state, &format!("        la      r2,{target}"));
        emit(state, "        jmp     (r2)");
    }
}

/// Emit a branch-if-true (carry flag set) to target.
///
/// Uses short `brt` for local labels. Uses long form for far targets.
pub fn emit_brt(state: &mut CodegenState, target: &str) {
    if is_local_label(target) {
        emit(state, &format!("        brt     {target}"));
    } else {
        let skip = new_label(state);
        emit(state, &format!("        brf     {skip}"));
        emit(state, &format!("        la      r2,{target}"));
        emit(state, "        jmp     (r2)");
        emit(state, &format!("{skip}:"));
    }
}

/// Emit a branch-if-false (carry flag clear) to target.
///
/// Uses short `brf` for local labels. Uses long form for far targets.
pub fn emit_brf(state: &mut CodegenState, target: &str) {
    if is_local_label(target) {
        emit(state, &format!("        brf     {target}"));
    } else {
        let skip = new_label(state);
        emit(state, &format!("        brt     {skip}"));
        emit(state, &format!("        la      r2,{target}"));
        emit(state, "        jmp     (r2)");
        emit(state, &format!("{skip}:"));
    }
}

/// Local labels (generated by `new_label`) start with 'L' followed by digits.
/// These are always within the current function and typically nearby.
/// Global/function labels (like `_main`, `_halt`) may be far away.
fn is_local_label(target: &str) -> bool {
    target.starts_with('L')
        && target.len() > 1
        && target[1..].chars().all(|c| c.is_ascii_digit())
}
